Postapic/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Postapic.Extensions;
using Postapic.Models;
using Postapic.Utils;
using Upload.Core;

namespace Postapic.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly DataContext _context;
    private readonly StorageManager _storageManager;
    private readonly IOptions<AppConfig> _appConfig;

    public List<Post> Posts { get; set; } = new();
    
    public PaginationModel Pagination { get; set; } = new();
    [FromQuery(Name = "page")] 
    public int Page { get; set; }
    
    [BindProperty] public int DeletePostId { get; set; }

    public IndexModel(ILogger<IndexModel> logger, DataContext context,
        StorageManager storageManager,
        IOptions<AppConfig> appConfig)
    {
        _logger = logger;
        _context = context;
        _storageManager = storageManager;
        _appConfig = appConfig;
    }

    public async Task OnGetAsync()
    {
        if (Page <= 0) Page = 1;
        
        var offset = (Page - 1) * _appConfig.Value.PageSize;
        Posts = await _context.Posts.AsNoTracking()
            .Where(p => !p.Draft)
            .Include(p => p.Medias)
            .Include(p => p.User)
            .OrderByDescending(p => p.Timestamp)
            .Skip(offset).Take(_appConfig.Value.PageSize)
            .ToListAsync();
        
        var count = await _context.Posts.Where(p => !p.Draft).CountAsync();
        var lastPage = (int)Math.Ceiling((float)count / _appConfig.Value.PageSize);
        
        Pagination = new PaginationModel
        {
            ShowBackwardControls = Page > 1,
            FirstPage = 1,
            PreviousPage = Page == 1 ? 1 : Page - 1,
            CurrentPage = Page,
            NextPage = Page == lastPage ? lastPage : Page + 1,
            LastPage = lastPage,
            ShowForwardControls = Page < lastPage
        };
    }

    public async Task<ActionResult> OnPostDeletePostAsync()
    {
        var userId = User.GetUserId(_appConfig.Value, _logger);
        if (userId is null) 
            return Page();
        
        var post = await _context.Posts.Include(p => p.Medias).FirstOrDefaultAsync(p => p.Id == DeletePostId);
        if (post == null) 
            return RedirectToPage("/Index");
        
        if (post.UserId != (int)userId)
            return RedirectToPage("/Index");
        
        if (DateTime.UtcNow.Subtract(post.Timestamp).TotalMinutes > 1) return RedirectToPage("/Index");

        _context.Posts.Remove(post);
        foreach (var postMedia in post.Medias)
        {
            // I'll just do replace and get over it
            var fileRef = await _storageManager.GetFile("primary", postMedia.Key.Replace("/media", ""));
            if (fileRef is null) continue;

            var ok = await fileRef.Delete();
            if (!ok)
            {
                _logger.LogWarning("Post is being deleted, but media {Key} could not be deleted!", postMedia.Key);
            }
        }
        await _context.SaveChangesAsync();
        return RedirectToPage("/Index");
    }

    public class PaginationModel
    {
        public bool ShowBackwardControls { get; set; }
        public int FirstPage { get; set; }
        public int PreviousPage { get; set; }
        public int CurrentPage { get; set; }
        public int NextPage { get; set; }
        public int LastPage { get; set; }
        public bool ShowForwardControls { get; set; }
    }
}

Postapic/Pages/PostPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Postapic.Extensions;
using Postapic.Models;
using Postapic.Models.Enums;
using Postapic.Utils;
using SixLabors.ImageSharp.Formats.Gif;
using Upload.Core;

namespace Postapic.Pages;

public class PostPage : PageModel
{
    private readonly DataContext _context;
    private readonly StorageManager _storageManager;
    private readonly IOptions<AppConfig> _appConfig;
    private readonly ILogger<PostPage> _logger;
    private readonly Size _maxSize;

    public PostPage(DataContext context, StorageManager storageManager, IOptions<AppConfig> appConfig,
        ILogger<PostPage> logger)
    {
        _context = context;
        _storageManager = storageManager;
        _appConfig = appConfig;
        _logger = logger;
        _maxSize = new Size(_appConfig.Value.MediaConfig.MaxWidth, _appConfig.Value.MediaConfig.MaxHeight);
    }
    
    [BindProperty] 
    public SubmitPostModel SubmitPostDto { get; set; }
    
    public Post DraftPost { get; set; }

    public async Task<ActionResult> OnPostCreateDraftAsync()
    {
        var userId = User.GetUserId(_appConfig.Value, _logger);
        if (userId is null)
        {
            return RedirectToPage("/Index");
        }
        
        if (Request.Form.Files.Count == 0) return RedirectToPage("/Index");;
        
        List<Media> medias = new();
        foreach (var formFile in Request.Form.Files)
        {
            await using var stream = formFile.OpenReadStream();
            using var image = await Image.LoadAsync(stream);
            {
                image.Mutate(i => i.Resize(new ResizeOptions
                {
                    Mode = ResizeMode.Max,
                    Size = _maxSize
                }).AutoOrient());
                
                var output = new MemoryStream();
                // Don't convert GIFs to webp format, just copy
                if (image.Metadata.DecodedImageFormat == GifFormat.Instance)
                {
                    // TODO: Resize do not mutate GIFs because we use original stream. SaveAsGif distorts GIF itself
                    stream.Position = 0;
                    await stream.CopyToAsync(output);
                }
                else
                {
                    await image.SaveAsWebpAsync(output);
                }
                
                output.Position = 0;
                var now = DateTime.UtcNow;
                var fileName = $"{now.Year}/{now.Month}/{now:yyyy-MM-ddThh-mm-ss}-{Random.Shared.Next(10, 100)}.webp";
                var fileRef = await _storageManager.CreateFile("primary", fileName, output);

                medias.Add(new Media
                {
                    Key = $"/media/{fileRef.Key}",
                    Height = image.Height,
                    Width = image.Width,
                    Type = MediaType.Image
                });
            }
        }

        var draftPost = new Post
        {
            Medias = medias,
            Permalink = $"DRAFT-{Random.Shared.Next(100, 1000)}",
            Timestamp = DateTime.UtcNow,
            Title = "DRAFT",
            UserId = (int)userId,
            Draft = true
        };

        await _context.Posts.AddAsync(draftPost);
        if (await _context.SaveChangesAsync() == 0)
        {
            return RedirectToPage("/Error");
        }

        DraftPost = draftPost;
        return Page();
    }

    public async Task<ActionResult> OnPostAddMediaToDraftAsync()
    {
        var userId = User.GetUserId(_appConfig.Value, _logger);
        if (userId is null)
        {
            return RedirectToPage("/Index");
        }
        
        if (Request.Form.Files.Count == 0) 
            return RedirectToPage("/Error");;

        var post = await _context.Posts.FirstOrDefaultAsync(p => p.Id == SubmitPostDto.DraftId);
        if (post is null)
            return RedirectToPage("/Error");

        List<Media> medias = new();
        foreach (var formFile in Request.Form.Files)
        {
            await using var stream = formFile.OpenReadStream();
            using var image = await Image.LoadAsync(stream);
            {
                image.Mutate(i => i.Resize(new ResizeOptions
                {
                    Mode = ResizeMode.Max,
                    Size = _maxSize
                }).AutoOrient());
                
                var output = new MemoryStream();
                // Don't convert GIFs to webp format, just copy
                if (image.Metadata.DecodedImageFormat == GifFormat.Instance)
                {
                    // TODO: Resize do not mutate GIFs because we use original stream. SaveAsGif distorts GIF itself
                    stream.Position = 0;
                    await stream.CopyToAsync(output);
                }
                else
                {
                    await image.SaveAsWebpAsync(output);
                }
                
                output.Position = 0;
                var now = DateTime.UtcNow;
                var fileName = $"{now.Year}/{now.Month}/{now:yyyy-MM-ddThh-mm-ss}-{Random.Shared.Next(10, 100)}.webp";
                var fileRef = await _storageManager.CreateFile("primary", fileName, output);

                medias.Add(new Media
                {
                    Key = $"/media/{fileRef.Key}",
                    Height = image.Height,
                    Width = image.Width,
                    Type = MediaType.Image,
                    PostId = post.Id
                });
            }
        }

        await _context.Medias.AddRangeAsync(medias);
        if (await _context.SaveChangesAsync() == 0)
            return RedirectToPage("/Error");

        DraftPost = await _context.Posts.AsNoTracking()
            .Include(p => p.Medias)
            .Include(p => p.User)
            .FirstAsync(p => p.Id == post.Id);
        return Page();
    }

    public async Task<ActionResult> OnPostPublishAsync()
    {
        var draft = await _context.Posts.FirstOrDefaultAsync(p => p.Id == SubmitPostDto.DraftId && p.Draft);
        if (draft is null) return RedirectToPage("/Error");
        
        draft.Permalink = null;
        if (!string.IsNullOrEmpty(SubmitPostDto.Permalink?.Trim()))
        {
            if (int.TryParse(SubmitPostDto.Permalink.Trim(), out var _))
            {
                ViewData["error-msg"] = "Permalink can't be a number. Please change and publish again";
                draft.Permalink = string.Empty;
                DraftPost = draft;
                return Page();
            }
            
            var samePermalink = await _context.Posts.FirstOrDefaultAsync(p => p.Permalink == SubmitPostDto.Permalink.Replace(' ', '_'));
            if (samePermalink is null)
            {
                draft.Permalink = SubmitPostDto.Permalink.Replace(' ', '_');
            }
            else
            {
                ViewData["error-msg"] = "Another post with the same permalink exists. Please change and publish again";
                draft.Permalink = string.Empty;
                DraftPost = draft;
                return Page();
            }
        }

        draft.Title = SubmitPostDto.Title;
        draft.Timestamp = DateTime.UtcNow;
        draft.Draft = false;
        await _context.SaveChangesAsync();
        return RedirectToPage("/Index");
    }

    public class SubmitPostModel
    {
        public int DraftId { get; set; }
        public string Title { get; set; } = "";
        public string? Permalink { get; set; }
    }
}

Postapic/Pages/Shared/PostComponent.cshtml
@using Microsoft.Extensions.Options
@model Post
@inject IOptions<AppConfig> AppConfig
@inject DataContext Db

@{
    var linkToPost = new Uri(new Uri(AppConfig.Value.BaseUrl), $"p/{Model.Permalink ?? Model.Id.ToString()}");
    var localTime = TimeZoneInfo.ConvertTime(Model.Timestamp, TimeZoneInfo.FindSystemTimeZoneById("Asia/Baku"));
}

<div class="post">
    <div class="post-header">
        <div class="post-meta">
            <span class="post-author">@Model.User.Username</span>
            <span class="post-time">@localTime.ToLocalTime().ToString("dd MMM yyyy, HH:mm")</span>
        </div>
        <div class="post-menu dropdown">
            <span class="dropdown-toggle">⋮</span>
            <ul class="dropdown-menu">
                <li>
                    <button onclick="copyLink(this, '@linkToPost');">Copy link</button>
                </li>
                @if (DateTime.UtcNow.Subtract(Model.Timestamp).TotalMinutes < 1 && userId == Model.UserId)
                {
                    <li>
                        <form asp-page="/Index" asp-page-handler="DeletePost" data-confirm="Do you want to delete post '@Model.Title'?">
                            <input type="hidden" asp-for="DeletePost" value="@Model.Id">
                            <button type="submit">Remove</button>
                        </form>
                    </li>
                }
            </ul>
        </div>
    </div>
    <h2>@Model.Title</h2>
    @if (Model.Medias.Count > 1)
    {
        <div class="media carousel">
            @foreach (var media in Model.Medias)
            {
                <img src="@media.Key" alt="Media for post with title @Model.Title">
            }
        </div>
        <div class="carousel-indicators">
            <span class="active"></span>
            @for (var i = 0; i < Model.Medias.Count - 1; i++)
            {
                <span></span>
            }
        </div>
    }
    else
    {
        <div class="media">
            <img src="@(Model.Medias.FirstOrDefault()?.Key ?? "https://http.cat/200")" alt="Media for post with title @Model.Title">
        </div>
    }
</div>

@code {

    private int DeletePostId;

}

Postapic/Pages/Shared/_Layout.cshtml
@inject IHttpContextAccessor ContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Postapic</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="~/manifest.json" />
</head>
<body>
<header>
    <nav>
        <a href="/" class="nav-logo">Post a pic!</a>
        
        <ul class="nav-menu container">
            <li><a href="/" class="@GetNavClass("/")">Explore</a></li>
            <li><a href="#" class="post-btn">Post&nbsp;a&nbsp;pic!</a></li>
        </ul>
        
        <div class="nav-user dropdown">
            @if (!User.Identity?.IsAuthenticated ?? true)
            {
                <span class="user-name"><a href="/login">Login</a></span>
            }
            else
            {
                <span class="dropdown-toggle user-name">@User.Identity!.Name</span>
                <ul class="dropdown-menu">
                    @if (User.IsInRole("Admin"))
                    {
                    <li><a href="/settings" class="@GetNavClass("/settings")">Settings</a></li>
                    }
                    <li><a href="/logout" class="@GetNavClass("/logout")">@User.Identity.Name - Log out</a></li>
                </ul>
            }
        </div>
    </nav>
</header>

<form class="upload-form hidden" asp-page="/PostPage" asp-page-handler="CreateDraft" method="post" enctype="multipart/form-data">
    <input type="file" name="files" accept="image/*" multiple />
</form>

<main role="main" class="pb-3">
    <div class="container">
        @RenderBody()
    </div>
</main>

<footer>
    <p>Post a pic! was made with 💕 and is licensed under the <a href="https://www.gnu.org/licenses/gpl-3.0.html">GNU GPL 3.0</a> · <a href="https://github.com/alvanrahimli/postapic/">Open source</a></p>
</footer>

<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@{
    string GetNavClass(string url)
    {
        return ContextAccessor.HttpContext?.Request.Path == url ? "active" : string.Empty;
    }
}