Postapic/Pages/Settings/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Postapic.Models;
using Postapic.Utils;

namespace Postapic.Pages.Settings;

public class SettingsPage : PageModel
{
    private readonly DataContext _context;
    public List<AppUser> UserList { get; set; } = new();
    
    [BindProperty] public CreateUserModel UserModel { get; set; }

    [BindProperty] public int DeleteUserId { get; set; }
    [BindProperty] public int ToggleAdminUserId { get; set; }

    public string UiMessage { get; set; } = string.Empty;

    public SettingsPage(DataContext context)
    {
        _context = context;
    }
    
    public async Task OnGetAsync()
    {
        UserList = await _context.Users.AsNoTracking().ToListAsync();
    }

    public async Task<ActionResult> OnPostCreateUserAsync()
    {
        UiMessage = "";
        
        var sameName = await _context.Users.AsNoTracking().FirstOrDefaultAsync(u => u.Username == UserModel.Username);
        if (sameName is not null)
        {
            UiMessage = "Could not create new user. Duplicate username";
            UserList = await _context.Users.AsNoTracking().ToListAsync();
            return Page();
        }
        
        var appUser = new AppUser
        {
            Username = UserModel.Username,
            PasswordHash = CryptoHelpers.GeneratePwdHash(UserModel.Password),
            IsAdmin = UserModel.IsAdmin
        };
        await _context.Users.AddAsync(appUser);
        if (await _context.SaveChangesAsync() == 0)
        {
            UiMessage = "Could not create user";
        }

        return RedirectToPage("/Settings/Index");
    }

    public async Task<ActionResult> OnPostDeleteUserAsync()
    {
        var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == DeleteUserId);
        if (user is null) return RedirectToPage("/Settings/Index");

        _context.Users.Remove(user);
        if (await _context.SaveChangesAsync() == 0)
        {
            UiMessage = "Could not delete user";
        }

        return RedirectToPage("/Settings/Index");
    }

    public async Task<ActionResult> OnPostToggleAdminAsync()
    {
        var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == ToggleAdminUserId);
        if (user is null) return RedirectToPage("/Settings/Index");

        user.IsAdmin = !user.IsAdmin;
        if (await _context.SaveChangesAsync() > 0)
        {
            return RedirectToPage("/Settings/Index");
        }
        
        ViewData["toggle-admin-msg"] = user.IsAdmin ? "Could not make user admin" : "Could not remove admin role";
        UserList = await _context.Users.AsNoTracking().ToListAsync();
        return Page();
    }

    public class CreateUserModel
    {
        public string Username { get; set; } = null!;
        public string Password { get; set; } = null!;
        public bool IsAdmin { get; set; }
    }
}

Postapic/Pages/Settings/Index.cshtml
@page "/settings"
@model Postapic.Pages.Settings.SettingsPage

@{
    Layout = "Shared/_Layout";
}

@if (ViewData["user-action-msg"] != null)
{
    <p class="notice">@ViewData["user-action-msg"]</p>
}
@if (ViewData["toggle-admin-msg"] != null)
{
    <p class="notice">@ViewData["toggle-admin-msg"]</p>
}

<section class="card user-table">
    <h1>Users</h1>
    <table>
        <thead>
        <tr>
            <th>Username</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var user in Model.UserList)
            {
                var isCurrentUser = User.Identity!.Name == user.Username;
                var confirmMessage = user.IsAdmin ? "Removing admin. Are you sure?" : $"Making '{user.Username}' admin. Are you sure?";
                <tr>
                    <td>@user.Username @(isCurrentUser ? "(you)" : "")</td>
                    <td>@(user.IsAdmin ? "Admin" : "User")</td>
                    <td>
                        @if (!isCurrentUser)
                        {
                            <form method="post" asp-page-handler="DeleteUser" data-confirm="Deleting '@user.Username'. Are you sure?">
                                <input type="hidden" asp-for="DeleteUserId" value="@user.Id">
                                <button type="submit" class="action-btn" disabled="@isCurrentUser">Delete</button>
                            </form>
                            <form method="post" asp-page-handler="ToggleAdmin" data-confirm="@confirmMessage">
                                <input type="hidden" asp-for="ToggleAdminUserId" value="@user.Id">
                                <button type="submit" class="action-btn" disabled="@isCurrentUser">Toggle role</button>
                            </form>
                        }
                        else
                        {
                            <span>-</span>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>

<section class="card create-user-form">
    <h1>Create New User</h1>
    <form method="post" asp-page-handler="CreateUser">
        <div class="input-group">
            <label asp-for="UserModel.Username">Username</label>
            <input type="text" asp-for="UserModel.Username" required>
        </div>
        <div class="input-group">
            <label asp-for="UserModel.Password">Password</label>
            <input type="password" asp-for="UserModel.Password" required>
        </div>
        <div class="input-group checkbox-group">
            <label asp-for="UserModel.IsAdmin">Is admin?</label>
            <input type="checkbox" asp-for="UserModel.IsAdmin">
        </div>
        
        <button type="submit" class="submit-btn">Create User</button>
    </form>
</section>