Postapic/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Postapic.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Postapic/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Postapic.Extensions;
using Postapic.Models;
using Postapic.Utils;
using Upload.Core;

namespace Postapic.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly DataContext _context;
    private readonly StorageManager _storageManager;
    private readonly IOptions<AppConfig> _appConfig;

    public List<Post> Posts { get; set; } = new();
    
    public PaginationModel Pagination { get; set; } = new();
    [FromQuery(Name = "page")] 
    public int Page { get; set; }
    
    [BindProperty] public int DeletePostId { get; set; }

    public IndexModel(ILogger<IndexModel> logger, DataContext context,
        StorageManager storageManager,
        IOptions<AppConfig> appConfig)
    {
        _logger = logger;
        _context = context;
        _storageManager = storageManager;
        _appConfig = appConfig;
    }

    public async Task OnGetAsync()
    {
        if (Page <= 0) Page = 1;
        
        var offset = (Page - 1) * _appConfig.Value.PageSize;
        Posts = await _context.Posts.AsNoTracking()
            .Where(p => !p.Draft)
            .Include(p => p.Medias)
            .Include(p => p.User)
            .OrderByDescending(p => p.Timestamp)
            .Skip(offset).Take(_appConfig.Value.PageSize)
            .ToListAsync();
        
        var count = await _context.Posts.Where(p => !p.Draft).CountAsync();
        var lastPage = (int)Math.Ceiling((float)count / _appConfig.Value.PageSize);
        
        Pagination = new PaginationModel
        {
            ShowBackwardControls = Page > 1,
            FirstPage = 1,
            PreviousPage = Page == 1 ? 1 : Page - 1,
            CurrentPage = Page,
            NextPage = Page == lastPage ? lastPage : Page + 1,
            LastPage = lastPage,
            ShowForwardControls = Page < lastPage
        };
    }

    public async Task<ActionResult> OnPostDeletePostAsync()
    {
        var userId = User.GetUserId(_appConfig.Value, _logger);
        if (userId is null) 
            return Page();
        
        var post = await _context.Posts.Include(p => p.Medias).FirstOrDefaultAsync(p => p.Id == DeletePostId);
        if (post == null) 
            return RedirectToPage("/Index");
        
        if (post.UserId != (int)userId)
            return RedirectToPage("/Index");
        
        if (DateTime.UtcNow.Subtract(post.Timestamp).TotalMinutes > 1) return RedirectToPage("/Index");

        _context.Posts.Remove(post);
        foreach (var postMedia in post.Medias)
        {
            // I'll just do replace and get over it
            var fileRef = await _storageManager.GetFile("primary", postMedia.Key.Replace("/media", ""));
            if (fileRef is null) continue;

            var ok = await fileRef.Delete();
            if (!ok)
            {
                _logger.LogWarning("Post is being deleted, but media {Key} could not be deleted!", postMedia.Key);
            }
        }
        await _context.SaveChangesAsync();
        return RedirectToPage("/Index");
    }

    public class PaginationModel
    {
        public bool ShowBackwardControls { get; set; }
        public int FirstPage { get; set; }
        public int PreviousPage { get; set; }
        public int CurrentPage { get; set; }
        public int NextPage { get; set; }
        public int LastPage { get; set; }
        public bool ShowForwardControls { get; set; }
    }
}

Postapic/Pages/Login.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Postapic.Models;
using Postapic.Utils;

namespace Postapic.Pages;

public class Login : PageModel
{
    private readonly DataContext _context;

    [BindProperty] public LoginModel LoginModel { get; set; }

    public string UiMessage { get; set; } = string.Empty;

    public Login(DataContext context)
    {
        _context = context;
    }
    
    public void OnGet()
    {
        
    }

    public async Task<ActionResult> OnPostAsync()
    {
        var sameNameUsers = await _context.Users.AsNoTracking()
            .Where(u => u.Username == LoginModel.Username).ToListAsync();

        var inputHash = CryptoHelpers.GeneratePwdHash(LoginModel.Password);
        var user = sameNameUsers.FirstOrDefault(u => u.PasswordHash == inputHash);
        if (user == null)
        {
            UiMessage = "Invalid login attempt.";
            return Page();
        }
        
        var claims = new List<Claim>
        {
            new(ClaimTypes.Name, user.Username),
            new(ClaimTypes.NameIdentifier, user.Id.ToString()),
            new(ClaimTypes.Role, user.IsAdmin ? "Admin" : "User")
        };
        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
            new ClaimsPrincipal(claimsIdentity), new AuthenticationProperties()
                { IsPersistent = true });

        return RedirectToPage("/Index");
    }
}

public class LoginModel
{
    public string Username { get; set; } = null!;
    public string Password { get; set; } = null!;
}

Postapic/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Postapic.Pages;

public class Logout : PageModel
{
    public void OnGet()
    {
        
    }

    public async Task<ActionResult> OnPostAsync()
    {
        await HttpContext.SignOutAsync();
        return RedirectToPage("/Index");
    }
}

Postapic/Pages/PostPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Postapic.Extensions;
using Postapic.Models;
using Postapic.Models.Enums;
using Postapic.Utils;
using SixLabors.ImageSharp.Formats.Gif;
using Upload.Core;

namespace Postapic.Pages;

public class PostPage : PageModel
{
    private readonly DataContext _context;
    private readonly StorageManager _storageManager;
    private readonly IOptions<AppConfig> _appConfig;
    private readonly ILogger<PostPage> _logger;
    private readonly Size _maxSize;

    public PostPage(DataContext context, StorageManager storageManager, IOptions<AppConfig> appConfig,
        ILogger<PostPage> logger)
    {
        _context = context;
        _storageManager = storageManager;
        _appConfig = appConfig;
        _logger = logger;
        _maxSize = new Size(_appConfig.Value.MediaConfig.MaxWidth, _appConfig.Value.MediaConfig.MaxHeight);
    }
    
    [BindProperty] 
    public SubmitPostModel SubmitPostDto { get; set; }
    
    public Post DraftPost { get; set; }

    public async Task<ActionResult> OnPostCreateDraftAsync()
    {
        var userId = User.GetUserId(_appConfig.Value, _logger);
        if (userId is null)
        {
            return RedirectToPage("/Index");
        }
        
        if (Request.Form.Files.Count == 0) return RedirectToPage("/Index");;
        
        List<Media> medias = new();
        foreach (var formFile in Request.Form.Files)
        {
            await using var stream = formFile.OpenReadStream();
            using var image = await Image.LoadAsync(stream);
            {
                image.Mutate(i => i.Resize(new ResizeOptions
                {
                    Mode = ResizeMode.Max,
                    Size = _maxSize
                }).AutoOrient());
                
                var output = new MemoryStream();
                // Don't convert GIFs to webp format, just copy
                if (image.Metadata.DecodedImageFormat == GifFormat.Instance)
                {
                    // TODO: Resize do not mutate GIFs because we use original stream. SaveAsGif distorts GIF itself
                    stream.Position = 0;
                    await stream.CopyToAsync(output);
                }
                else
                {
                    await image.SaveAsWebpAsync(output);
                }
                
                output.Position = 0;
                var now = DateTime.UtcNow;
                var fileName = $"{now.Year}/{now.Month}/{now:yyyy-MM-ddThh-mm-ss}-{Random.Shared.Next(10, 100)}.webp";
                var fileRef = await _storageManager.CreateFile("primary", fileName, output);

                medias.Add(new Media
                {
                    Key = $"/media/{fileRef.Key}",
                    Height = image.Height,
                    Width = image.Width,
                    Type = MediaType.Image
                });
            }
        }

        var draftPost = new Post
        {
            Medias = medias,
            Permalink = $"DRAFT-{Random.Shared.Next(100, 1000)}",
            Timestamp = DateTime.UtcNow,
            Title = "DRAFT",
            UserId = (int)userId,
            Draft = true
        };

        await _context.Posts.AddAsync(draftPost);
        if (await _context.SaveChangesAsync() == 0)
        {
            return RedirectToPage("/Error");
        }

        DraftPost = draftPost;
        return Page();
    }

    public async Task<ActionResult> OnPostAddMediaToDraftAsync()
    {
        var userId = User.GetUserId(_appConfig.Value, _logger);
        if (userId is null)
        {
            return RedirectToPage("/Index");
        }
        
        if (Request.Form.Files.Count == 0) 
            return RedirectToPage("/Error");;

        var post = await _context.Posts.FirstOrDefaultAsync(p => p.Id == SubmitPostDto.DraftId);
        if (post is null)
            return RedirectToPage("/Error");

        List<Media> medias = new();
        foreach (var formFile in Request.Form.Files)
        {
            await using var stream = formFile.OpenReadStream();
            using var image = await Image.LoadAsync(stream);
            {
                image.Mutate(i => i.Resize(new ResizeOptions
                {
                    Mode = ResizeMode.Max,
                    Size = _maxSize
                }).AutoOrient());
                
                var output = new MemoryStream();
                // Don't convert GIFs to webp format, just copy
                if (image.Metadata.DecodedImageFormat == GifFormat.Instance)
                {
                    // TODO: Resize do not mutate GIFs because we use original stream. SaveAsGif distorts GIF itself
                    stream.Position = 0;
                    await stream.CopyToAsync(output);
                }
                else
                {
                    await image.SaveAsWebpAsync(output);
                }
                
                output.Position = 0;
                var now = DateTime.UtcNow;
                var fileName = $"{now.Year}/{now.Month}/{now:yyyy-MM-ddThh-mm-ss}-{Random.Shared.Next(10, 100)}.webp";
                var fileRef = await _storageManager.CreateFile("primary", fileName, output);

                medias.Add(new Media
                {
                    Key = $"/media/{fileRef.Key}",
                    Height = image.Height,
                    Width = image.Width,
                    Type = MediaType.Image,
                    PostId = post.Id
                });
            }
        }

        await _context.Medias.AddRangeAsync(medias);
        if (await _context.SaveChangesAsync() == 0)
            return RedirectToPage("/Error");

        DraftPost = await _context.Posts.AsNoTracking()
            .Include(p => p.Medias)
            .Include(p => p.User)
            .FirstAsync(p => p.Id == post.Id);
        return Page();
    }

    public async Task<ActionResult> OnPostPublishAsync()
    {
        var draft = await _context.Posts.FirstOrDefaultAsync(p => p.Id == SubmitPostDto.DraftId && p.Draft);
        if (draft is null) return RedirectToPage("/Error");
        
        draft.Permalink = null;
        if (!string.IsNullOrEmpty(SubmitPostDto.Permalink?.Trim()))
        {
            if (int.TryParse(SubmitPostDto.Permalink.Trim(), out var _))
            {
                ViewData["error-msg"] = "Permalink can't be a number. Please change and publish again";
                draft.Permalink = string.Empty;
                DraftPost = draft;
                return Page();
            }
            
            var samePermalink = await _context.Posts.FirstOrDefaultAsync(p => p.Permalink == SubmitPostDto.Permalink.Replace(' ', '_'));
            if (samePermalink is null)
            {
                draft.Permalink = SubmitPostDto.Permalink.Replace(' ', '_');
            }
            else
            {
                ViewData["error-msg"] = "Another post with the same permalink exists. Please change and publish again";
                draft.Permalink = string.Empty;
                DraftPost = draft;
                return Page();
            }
        }

        draft.Title = SubmitPostDto.Title;
        draft.Timestamp = DateTime.UtcNow;
        draft.Draft = false;
        await _context.SaveChangesAsync();
        return RedirectToPage("/Index");
    }

    public class SubmitPostModel
    {
        public int DraftId { get; set; }
        public string Title { get; set; } = "";
        public string? Permalink { get; set; }
    }
}

Postapic/Pages/SinglePost.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Postapic.Models;

namespace Postapic.Pages;

public class SinglePost : PageModel
{
    private readonly DataContext _context;
    public Post? Post { get; set; }

    public SinglePost(DataContext context)
    {
        _context = context;
    }
    
    public async Task<ActionResult> OnGet(string idOrPermalink)
    {
        var query = _context.Posts.Include(p => p.Medias).Include(p => p.User);
        var isInt = int.TryParse(idOrPermalink, out var id);
        if (isInt)
        {
            Post = await query.FirstOrDefaultAsync(p => p.Id == id);
        }
        else
        {
            Post = await query.FirstOrDefaultAsync(p => p.Permalink == idOrPermalink);
        }

        if (Post == null) return RedirectToPage("/Error");
        
        return Page();
    }
}

Postapic/Pages/Index.cshtml
@page "/"
@using Microsoft.Extensions.Options
@using Postapic.Extensions
@model IndexModel
@inject IOptions<AppConfig> AppConfig
@inject ILogger<IndexModel> Logger
@{
    ViewData["Title"] = "Home page";
    var userId = User.GetUserId(AppConfig.Value, Logger) ?? -1;
}

<div class="feed">
    @foreach (var post in Model.Posts)
    {
        <partial name="Shared/PostComponent" model="post" />
        
        var linkToPost = new Uri(new Uri(AppConfig.Value.BaseUrl), $"p/{post.Permalink ?? post.Id.ToString()}");
        <div class="post">
            <div class="post-header">
                <div class="post-meta">
                    <span class="post-author">@post.User.Username</span>
                    @{
                        var localTime = TimeZoneInfo.ConvertTime(post.Timestamp, TimeZoneInfo.FindSystemTimeZoneById("Asia/Baku"));
                    }
                    <span class="post-time">@localTime.ToLocalTime().ToString("dd MMM yyyy, HH:mm")</span>
                </div>
                <div class="post-menu dropdown">
                    <span class="dropdown-toggle">⋮</span>
                    <ul class="dropdown-menu">
                        <li>
                            <button onclick="copyLink(this, '@linkToPost');">Copy link</button>
                        </li>
                        @if (DateTime.UtcNow.Subtract(post.Timestamp).TotalMinutes < 1 && userId == post.UserId)
                        {
                            <li>
                                <form asp-page="/Index" asp-page-handler="DeletePost" data-confirm="Do you want to delete post '@post.Title'?">
                                    <input type="hidden" asp-for="DeletePostId" value="@post.Id">
                                    <button type="submit">Remove</button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <h2>@post.Title</h2>
            @if (post.Medias.Count > 1)
            {
                <div class="media carousel">
                    @foreach (var media in post.Medias)
                    {
                        <img src="@media.Key" alt="Media for post with title @post.Title">
                    }
                </div>
                <div class="carousel-indicators">
                    <span class="active"></span>
                    @for (var i = 0; i < post.Medias.Count - 1; i++)
                    {
                        <span></span>
                    }
                </div>
            }
            else
            {
                <div class="media">
                    <img src="@(post.Medias.FirstOrDefault()?.Key ?? "https://http.cat/200")" alt="Media for post with title @post.Title">
                </div>
            }
        </div>
    }
    
    <div class="pagination">
        @if (Model.Pagination.ShowBackwardControls)
        {
            <a href="?page=@Model.Pagination.FirstPage">&lt;&lt;</a><span class="sep"></span>
            <a href="?page=@Model.Pagination.PreviousPage">&lt;</a><span class="sep"></span>
        }
        
        <a>@Model.Pagination.CurrentPage</a><span class="sep"></span>
        
        @if (Model.Pagination.ShowForwardControls)
        {
            <a href="?page=@Model.Pagination.NextPage">&gt;</a><span class="sep"></span>
            <a href="?page=@Model.Pagination.LastPage">&gt;&gt;</a>
        }
    </div>
</div>

@{
    
}

Postapic/Pages/Login.cshtml
@page "/login"
@model Postapic.Pages.Login

@{
    Layout = "Shared/_Layout";
}



<section class="card post-form">
    @if (!string.IsNullOrEmpty(Model.UiMessage))
    {
        <h1 class="warning">@Model.UiMessage</h1>
    }
    else
    {
        <h1>Log in to your account</h1>
    }
    <form method="POST">
        <div class="input-group">
            <label asp-for="LoginModel.Username">Username</label>
            <input type="text" asp-for="LoginModel.Username" required>
        </div>
        <div class="input-group">
            <label asp-for="LoginModel.Password">Password</label>
            <input type="password" asp-for="LoginModel.Password" required>
        </div>
        <button type="submit" class="submit-btn">Login</button>
    </form>
</section>

Postapic/Pages/Logout.cshtml
@page "/logout"
@model Postapic.Pages.Logout

@{
    Layout = "Shared/_Layout";
}

<section class="card post-form">
    <h1>Are you sure?</h1>
    <form method="POST">
        <button type="submit" class="submit-btn">Yes, log me out</button>
    <a href="/" style="margin-left: 1em;">Nope, take me back</a>
    </form>
</section>

Postapic/Pages/PostPage.cshtml
@page "/post"
@model Postapic.Pages.PostPage

@{
    Layout = "Shared/_Layout";
}

<section class="card post-form">
    @if (ViewData["error-msg"] is not null)
    {
        <h2 class="warning">@ViewData["error-msg"]</h2>
    }
    else
    {
        <h1>Publish your post</h1>
    }
    <form id="add-media-form" class="hidden" asp-page="/PostPage" asp-page-handler="AddMediaToDraft" method="post" enctype="multipart/form-data">
        <input id="add-media-input" type="file" name="files" accept="image/*" multiple />
        <input type="hidden" asp-for="SubmitPostDto.DraftId" value="@Model.DraftPost.Id" />
    </form>
    
    <form method="post" asp-page-handler="Publish" autocomplete="off">
        <div class="input-group">
            <label asp-for="SubmitPostDto.Title">Title</label>
            <input type="text" asp-for="SubmitPostDto.Title" required placeholder="Explain the post.." autofocus="autofocus" autocomplete="no">
            <p class="input-tip">You can delete within a minute after publishing</p>
        </div>
        <div class="input-group">
            <div class="media carousel">
                @foreach (var m in Model.DraftPost.Medias)
                {
                    <img src="@m.Key" alt="Media for a draft post">
                }
                
                <div class="add-media">
                    <button type="button" id="add-media-btn">+ New Media</button>
                </div>
            </div>
            <div class="carousel-indicators">
                <span class="active"></span>
                @for (var i = 0; i < Model.DraftPost.Medias.Count - 1; i++)
                {
                    <span></span>
                }
                
                @* For new image button *@
                <span></span>
            </div>
        </div>
        
        <details style="margin-bottom: 1rem">
            <summary>Advanced</summary>
            <div class="input-group">
                <input type="text" asp-for="SubmitPostDto.Permalink" placeholder="Enter a permalink">
            </div>
        </details>

        <input type="hidden" asp-for="SubmitPostDto.DraftId" value="@Model.DraftPost.Id">
        <button type="submit" class="submit-btn">Publish</button>
    </form>
</section>

@section Scripts
{
    <script>
    !(function () {
        const postBtn = document.querySelector("#add-media-btn");
        const uploadForm = document.querySelector("#add-media-form");
        const fileInput = uploadForm.querySelector('#add-media-input');
        postBtn.addEventListener("click", (el) => {
            fileInput.click();
        });
        fileInput.addEventListener("change", () => {
            if (fileInput.files.length > 0) {
                uploadForm.submit();
            }
        });
    })();
    </script>
}

Postapic/Pages/SinglePost.cshtml
@page "/p/{idOrPermalink}"
@model Postapic.Pages.SinglePost

@{
    Layout = "Shared/_Layout";
}

<div class="feed">
    <partial name="Shared/PostComponent" model="@Model.Post"/>
</div>